### ISSUE TITLE
Did you get this almost working on real time ?

### ISSUE THREAD

**Issue by shamanez** [datitran/object_detector_app#20]
I ran this code but still  there's this lag. It may be wrong with my machine . I ran this in my laptop with 2GB 920M and 8GB ram.

**Comment by datitran** [comment]
Hmm have you checked your RAM utilisation? I have 16GB memory. Usually when I run it with a lot of applications open at the same time, things are slow sometimes as well but this applies for any application.

**Comment by shamanez** [comment]
Yeah . I think you are right .

**Comment by datitran** [comment]
@shamanez can you try this [new implementation of mine](https://github.com/datitran/object_detector_app/blob/master/object_detection_multithreading.py). It might be performing better on your machine since this one is just drawing the boxes on the image instead of visualizing the images and the boxes together.
