### ISSUE TITLE
about fps

### ISSUE THREAD

**Issue by wm901115nwpu** [datitran/object_detector_app#6]
My fps rate is1.36 using cpu,is it normal?Why are your implement is 0.11?

**Comment by datitran** [comment]
Hey that's very low. You should look into it. My approx. FPS rate is on average 6. If I adjust this for the overhead time of Tensorflow starting the session, it is 10. I'm working on increasing the fps rate as I said in my article, it is not optimal but I basically started with a very low FPS rate when doing a naive implementation. So the rate I have now is actually pretty good compared to what I had at the beginning.

Here are some ideas that I have to improve the performance:
1. Skip frames of the video stream could help since there are moments where nothing is happening
2. Resizing the input image aka video stream and then rescaling the boxes. For a current project where I use dlib and its face detector, I use this trick and the performance is super awesome
3. Use TF Queues instead of sess.run but not sure if this will help for CPU, for GPU this definitely should help

Yeh, I hope to find some time to do it or some others could also implement it.
